version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ombi_server_1
      APP_PORT: 3579
      PROXY_AUTH_WHITELIST: "/api/*"
  server:
    image: lscr.io/linuxserver/ombi:4.44.1@sha256:ecfa94a4b8ad178c0f55e1b5b2ae883963fb1d8dc4afe44d32c177ad93a4b72c
    restart: on-failure
    environment:  
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=/
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
