version: "3.7"

services:
  server:
    image: linuxserver/emby:4.8.10@sha256:29e939f7a51aac5d1d9f1149ce3faa1f937aea9661aa543a427bc2c280e84731
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    network_mode: host
    environment:  
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - GIDLIST=100
    # Currently running in host network mode to allow for UPnP discovery (Emby DLNA server) and so that Docker does not complain about port 1900/udp being in use (can be shared, for example with Home Assistant).
    # ports:
    #   - 8096:8096
    #   - 8920:8920
    #   # Network discovery
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - /opt/vc/lib:/opt/vc/lib
